fos_elastica:
    clients:
        default:
            host: localhost
            port: 9200
    indexes:
        global:
            finder: ~

knp_paginator:
    page_range: 10
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v3_pagination.html.twig'
